### ISSUE TITLE
Query nested properties

### ISSUE THREAD

**Issue by juncoding** [strongloop/loopback-filters#10]
I'm not sure it's a bug or a new feature, but the behavior is not same as loopback find/findOne. 

=== Sample Code ===

```js
var applyFilter = require('loopback-filters');
var data = [
    {foo: [{name: 'bar'}, {name: 'bar2'}]},
    {bat: [{name: 'baz'}]},
    {foo: [{name: 'bar'}]}
];
var filter = {where: {"foo.name": 'bar'}};
var filtered = applyFilter(data, filter);
console.log(filtered);
```

=== Expected result ===

```
[ {foo: [{name: 'bar'}, {name: 'bar2'}] }, { foo: [{name: 'bar'} ]
```

=== Actual result ===

```
[]
```

but I use loopback model.find/findOne, I can get expected result. 

Please help.  Thanks.

**Comment by bajtos** [comment]
I think you are looking for support for querying nested properties, which was added to loopback-datasource-juggler (and thus `find`/`findOne` methods) via https://github.com/strongloop/loopback-datasource-juggler/pull/1239 and possibly other pull requests related to https://github.com/strongloop/loopback/issues/517. 

Ideally, loopback-datasource-juggler's memory connector would be using loopback-filters under the hood and there was only a single place where to add support for new filtering features. Unfortunately we haven't had bandwidth to do that change, and as a result loopback-filters is always behind loopback capabilities. Any volunteers to contribute this change?

As a short-term workaround, we can always port https://github.com/strongloop/loopback-datasource-juggler/pull/1239 (and other related pull requests) from juggler to this module. We don't have bandwidth for this task ourselves, but we are happy to help you if you decide to contribute this feature.

**Comment by bajtos** [comment]
I created a new issue in juggler to keep track of the work of using loopback-filters under the hood: https://github.com/strongloop/loopback-datasource-juggler/issues/1529
