### ISSUE TITLE
Add browser / bower support

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-filters#2]
This module is probably most useful in the context of a browser where:
- you have a loopback backend
- you want to further filter data from the backend using the same syntax as the filter you are sending to the server.

We should support:
- browserify require (almost certain this will just work)
- standalone umd style with global fallback (we can use browserify stand-alone for this)
- install via bower

/cc @bajtos @jtary @anthonyettinger @seanbrookes

**Comment by bajtos** [comment]
:+1:

**Comment by bajtos** [comment]
We don't have bandwidth to work on this ourselves. If there is anybody willing to contribute necessary changes to make loopback-filters work in the browser (assuming it does not work OOTB), then we are happy to accept such contribution.
