### ISSUE TITLE
There something wrong in Fields filter REST API 

### ISSUE THREAD

**Issue by bestvow** [strongloop/loopback-filters#24]
With introduce `filter[fields][propertyName]=<true|false>`
![image](https://user-images.githubusercontent.com/24888709/33797199-d105af7e-dd3e-11e7-96e3-e0660b5dd78f.png)
![image](https://user-images.githubusercontent.com/24888709/33797200-d29364b2-dd3e-11e7-9caa-1a92e385e40d.png)
![image](https://user-images.githubusercontent.com/24888709/33797201-d3e33bbc-dd3e-11e7-9b03-43d4a08e024c.png)
Do not add everything if some fields you don't want to see even a `flase` ?

**Comment by bestvow** [comment]
The JSON format `?filter={"fields":{"id":true,"name":false,"city":true}}` is prospective
![image](https://user-images.githubusercontent.com/24888709/33797267-ebd30fb2-dd3f-11e7-9cda-4e1b6769d4cc.png)
`

**Comment by bajtos** [comment]
Hello, this module does not provide any REST API. If the problem is still relevant, then please open a new issue in [loopback](https://github.com/strongloop/loopback/issues/new) and provide a small app reproducing the problem - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
